root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/chronicle ./cmd/chronicle"
  bin = "./tmp/chronicle"
  args_bin = ["admin", "--dev"]
  include_ext = ["go"]
  exclude_dir = ["tmp", "node_modules", ".git", ".depbot"]
  delay = 500

[misc]
  clean_on_exit = true
