package prompts

import (
	"strings"
	"testing"
)

// L6 — Real agent pack creation test.
// This pack was generated by a haiku agent given the authoring guide + Django sample files.
// The test validates that the agent-created pack is usable by the system.

const haikuDjangoPack = `# DJANGO EXTRACTION RULES

Apply when file imports from ` + "`django.*`" + ` or uses Django patterns.

## Views (→ endpoint facts)

URL patterns in urls.py define routes:
- Function-based view: ` + "`" + `path('orders/', views.create_order, name='create-order')` + "`" + ` => ` + "`" + `{"kind":"endpoint","method":"POST","target":"/orders"}` + "`" + `
- Class-based view: ` + "`" + `class OrderListView(APIView):` + "`" + ` with ` + "`" + `def get(self, request):` + "`" + ` => ` + "`" + `{"kind":"endpoint","method":"GET","target":"/orders"}` + "`" + `
- DRF ViewSets: generates endpoints for list/create/retrieve/update/destroy

## Models (→ model/enum facts)

- ` + "`" + `class Order(models.Model):` + "`" + ` => ` + "`" + `{"kind":"model","to":"Order"}` + "`" + `
- ` + "`" + `class OrderStatus(models.TextChoices):` + "`" + ` => ` + "`" + `{"kind":"enum","to":"OrderStatus"}` + "`" + `
- ` + "`" + `customer = models.ForeignKey(Customer, ...)` + "`" + ` => ` + "`" + `{"kind":"model_relation","from":"Order","to":"Customer"}` + "`" + `

## Model usage (→ uses_model facts)

- ` + "`" + `Order.objects.filter(...)` + "`" + ` => ` + "`" + `{"kind":"uses_model","to":"Order"}` + "`" + `
- ` + "`" + `Customer.objects.get(id=...)` + "`" + ` => ` + "`" + `{"kind":"uses_model","to":"Customer"}` + "`" + `

## Dependency injection (→ injects facts)

- ` + "`" + `self.order_service = OrderService()` + "`" + ` => ` + "`" + `{"kind":"injects","to":"OrderService"}` + "`" + `

## Service calls (→ calls_service facts)

- ` + "`" + `self.payment_service.charge(order)` + "`" + ` => ` + "`" + `{"kind":"calls_service","to":"PaymentService","method":"charge"}` + "`" + `

## HTTP calls (→ http_call facts)

- ` + "`" + `requests.post('https://api.stripe.com/v1/charges', ...)` + "`" + ` => ` + "`" + `{"kind":"http_call","target":"https://api.stripe.com/v1/charges","method":"POST"}` + "`" + `

## Celery tasks (→ produces/consumes facts)

- ` + "`" + `@shared_task def send_order_confirmation(order_id):` + "`" + ` => ` + "`" + `{"kind":"consumes","to":"send_order_confirmation","method":"send_order_confirmation"}` + "`" + `
- ` + "`" + `send_order_confirmation.delay(order.id)` + "`" + ` => ` + "`" + `{"kind":"produces","to":"send_order_confirmation","method":"delay"}` + "`" + `

## Do NOT extract

- Django admin classes
- Migration files
- Management commands
- Test files and fixtures
- Settings/configuration files
- Serializers
`

func TestL6_HaikuCreatedDjangoPack_PassesValidation(t *testing.T) {
	invalid := ValidateCustomPack(haikuDjangoPack)
	if len(invalid) > 0 {
		t.Errorf("haiku-created Django pack has invalid kinds: %v", invalid)
	}
}

func TestL6_HaikuCreatedDjangoPack_HasRequiredSections(t *testing.T) {
	required := []string{
		"endpoint",        // maps views to endpoints
		"model",           // maps Django models
		"enum",            // maps TextChoices
		"model_relation",  // maps ForeignKey
		"uses_model",      // maps ORM queries
		"calls_service",   // maps service calls
		"http_call",       // maps requests.get/post
		"produces",        // maps Celery .delay()
		"consumes",        // maps @shared_task
		"Do NOT extract",  // has reject guidance
	}
	for _, s := range required {
		if !strings.Contains(haikuDjangoPack, s) {
			t.Errorf("pack missing required section/kind: %q", s)
		}
	}
}

func TestL6_HaikuCreatedDjangoPack_IDIsValid(t *testing.T) {
	if err := ValidatePackID("custom/django"); err != "" {
		t.Errorf("custom/django ID rejected: %s", err)
	}
}

func TestL6_HaikuCreatedDjangoPack_ComposesWithCore(t *testing.T) {
	composed := FactSchema + "\n\n---\n\n" + haikuDjangoPack

	if !strings.Contains(composed, "FACT SCHEMA") {
		t.Error("composed guide missing core")
	}
	if !strings.Contains(composed, "DJANGO EXTRACTION RULES") {
		t.Error("composed guide missing Django adapter")
	}
}

func TestL6_HaikuCreatedDjangoPack_NoInventedKinds(t *testing.T) {
	// Specifically check that haiku didn't invent Django-specific kinds
	forbidden := []string{
		"django_view", "django_model", "django_admin",
		"celery_task", "orm_query", "url_pattern",
		"viewset", "serializer", "middleware",
	}
	for _, kind := range forbidden {
		if strings.Contains(haikuDjangoPack, `"kind":"`+kind+`"`) {
			t.Errorf("pack contains invented kind: %s", kind)
		}
	}
}
